spring:
  application:
    name: Greet-API
  boot:
    admin:
      client:
        url: http://localhost:8082/

server:
  port: 8084
  
  
management:
  endpoints:
    web:
      exposure:
        include: "*"
